-- ============================================================
-- MADHURAVANA FIRST ADMIN DEVICE BOOTSTRAP
-- ============================================================
-- Run this AFTER the device-lock SQL you already ran.
--
-- IMPORTANT:
-- This removes the automatic "first browser becomes admin" behavior
-- from the login flow by adding a one-time 6-digit Setup PIN.
--
-- The PIN is generated below and displayed ONLY in this SQL Editor
-- session. It is not sent to the browser and is not stored in plain
-- text in the permanent database.
--
-- First device:
--   Email + Password -> Setup PIN -> Primary Device
--
-- Later devices:
--   Email + Password -> 6-digit code generated by primary device
-- ============================================================

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

create table if not exists public.admin_bootstrap_codes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  code_hash text not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists admin_bootstrap_codes_user_idx
on public.admin_bootstrap_codes(user_id, created_at desc);

alter table public.admin_bootstrap_codes enable row level security;
revoke all on public.admin_bootstrap_codes from anon, authenticated;

-- The first admin device can only be claimed by the authenticated user
-- who is already present in public.admin_users.
create or replace function public.claim_primary_admin_device_with_bootstrap_code(
  p_code text,
  p_device_token text,
  p_device_label text default 'Admin browser'
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  code_row public.admin_bootstrap_codes%rowtype;
  existing_count integer;
  device_id uuid;
begin
  if auth.uid() is null or not public.is_admin() then
    return jsonb_build_object('ok', false, 'reason', 'not-admin');
  end if;

  if p_device_token is null or length(trim(p_device_token)) < 32 then
    return jsonb_build_object('ok', false, 'reason', 'invalid-device-token');
  end if;

  select count(*)::integer
  into existing_count
  from public.admin_devices
  where user_id = auth.uid()
    and revoked_at is null;

  if existing_count > 0 then
    return jsonb_build_object('ok', false, 'reason', 'primary-device-already-registered');
  end if;

  select *
  into code_row
  from public.admin_bootstrap_codes
  where user_id = auth.uid()
    and code_hash = encode(
      extensions.digest(trim(p_code)::text, 'sha256'::text),
      'hex'
    )
    and used_at is null
    and expires_at > now()
  order by created_at desc
  limit 1;

  if code_row.id is null then
    return jsonb_build_object('ok', false, 'reason', 'invalid-or-expired-setup-pin');
  end if;

  update public.admin_bootstrap_codes
  set used_at = now()
  where id = code_row.id
    and used_at is null;

  if not found then
    return jsonb_build_object('ok', false, 'reason', 'setup-pin-already-used');
  end if;

  insert into public.admin_devices
  (
    user_id,
    device_token_hash,
    device_label,
    is_primary
  )
  values
  (
    auth.uid(),
    encode(
      extensions.digest(trim(p_device_token)::text, 'sha256'::text),
      'hex'
    ),
    left(coalesce(nullif(trim(p_device_label), ''), 'Admin browser'), 120),
    true
  )
  returning id into device_id;

  return jsonb_build_object(
    'ok', true,
    'device_id', device_id,
    'primary', true
  );
end;
$$;

revoke all
on function public.claim_primary_admin_device_with_bootstrap_code(text, text, text)
from public;

grant execute
on function public.claim_primary_admin_device_with_bootstrap_code(text, text, text)
to authenticated;

-- ------------------------------------------------------------
-- Generate a fresh one-time 6-digit Setup PIN for the first
-- authorized admin user.
-- ------------------------------------------------------------
-- Change this email to the EXACT Supabase Auth email that is in
-- public.admin_users before running this section.
-- ------------------------------------------------------------

do $$
declare
  v_email text := 'YOUR_ADMIN_EMAIL_HERE';
  v_user_id uuid;
  v_pin text;
  v_hash text;
begin
  select id
  into v_user_id
  from auth.users
  where lower(email) = lower(v_email)
  limit 1;

  if v_user_id is null then
    raise exception 'Admin email not found. Change YOUR_ADMIN_EMAIL_HERE to your real Supabase Auth email.';
  end if;

  if not exists (
    select 1
    from public.admin_users
    where user_id = v_user_id
  ) then
    raise exception 'This Auth user is not in public.admin_users.';
  end if;

  if exists (
    select 1
    from public.admin_devices
    where user_id = v_user_id
      and revoked_at is null
  ) then
    raise exception 'This admin already has an active authorized device. Do not create a bootstrap PIN unless you intentionally want to reset the device setup.';
  end if;

  v_pin := lpad(
    (
      (
        get_byte(extensions.gen_random_bytes(4), 0)::bigint * 16777216 +
        get_byte(extensions.gen_random_bytes(4), 0)::bigint * 65536 +
        get_byte(extensions.gen_random_bytes(4), 0)::bigint * 256 +
        get_byte(extensions.gen_random_bytes(4), 0)::bigint
      ) % 1000000
    )::text,
    6,
    '0'
  );

  v_hash := encode(
    extensions.digest(v_pin::text, 'sha256'::text),
    'hex'
  );

  delete from public.admin_bootstrap_codes
  where user_id = v_user_id
    and used_at is null;

  insert into public.admin_bootstrap_codes
  (
    user_id,
    code_hash,
    expires_at
  )
  values
  (
    v_user_id,
    v_hash,
    now() + interval '24 hours'
  );

  create temp table if not exists madhuravana_bootstrap_pin (
    setup_pin text
  ) on commit preserve rows;

  delete from madhuravana_bootstrap_pin;
  insert into madhuravana_bootstrap_pin values (v_pin);
end;
$$;

select setup_pin as "YOUR FIRST ADMIN SETUP PIN"
from madhuravana_bootstrap_pin;

-- ============================================================
-- IMPORTANT:
-- The SELECT result above is the ONLY place the fresh PIN is shown.
-- Keep it private. Do not put it in JavaScript.
-- ============================================================
